specialty_labels = [
    'E-commerce',
    'SaaS solutions and Cloud solutions',
    'Marketing and advertising services',
    'Financial services and investment',
    'IT support and cybersecurity',
    'Market Research',
    'Recruitment and human resources',
    'Sustainability and ethical production',
    'Mobile applications',
    'Artificial Intelligence and Machine Learning',
    'Social Media Marketing and Management',
    'Augmented and Virtual Reality',
    'Energy Solutions (Solar Energy)',
    'Customization and Personalization',
    'Customer Service/Experience'
    'Social Media',
    'Analytics'
]

category_labels = [
    'Software/IT',
    'E-commerce',
    'Marketing/Advertising',
    'Consulting/Services',
    'Human Resources',
    'Artificial Intelligence',
    'Social Media',
    'Mobile/Apps',
    'Financial Services',
    'Retail',
    'Education/ Learning',
    'Real Estate',
    'Manufacturing',
    'Healthcare/Wellness',
    'Transportation/Logistics',
    'Hospitality',
    'Market Research',
    'Saas',
    'Public Relations'
]

industry_labels = [
    'Technology and Software',
    'Marketing and Advertising',
    'Finance and Investment',
    'Consulting and Professional Services',
    'Real Estate and Property',
    'Retail and Consumer Goods',
    'Hospitality and Tourism',
    'Healthcare and Medical Devices',
    'Transportation and Logistics',
    'Education',
    'Non-profit',
    'Energy & Utilities',
    'Telecommunications',
    'Agriculture',
    'Environmental',
    'Legal Services'
]

tech_labels = [
    'customer relationship',
    'advertising',
    'video sharing and streaming',
    'website hosting',
    'website analytics',
    'email marketing',
    'live chat and messaging',
    'cloud computing',
    'event management',
    'payment gateways',
    'human resource management',
    'programming languages',
    'e-commerce platforms'
]

tech_stack_dict = {
  "Google AdWords": ["advertising"],
  "LinkedIn Ads": ["advertising"],
  "HubSpot": ["customer relationship", "email marketing", "website analytics", "event management"],
  "YouTube": ["video sharing and streaming"],
  "Amazon Route 53": ["cloud computing", "website hosting"],
  "Zendesk": ["customer relationship", "live chat and messaging"],
  "Hubspot Form Builder": ["customer relationship", "email marketing"],
  "New Relic": ["cloud computing", "website analytics"],
  "Sendgrid": ["email marketing"],
  "WordPress": ["website hosting", "e-commerce platforms"],
  "Unbounce": ["website analytics", "advertising"],
  "Amazon Cloudfront": ["cloud computing", "website hosting"],
  "Salesforce": ["customer relationship", "human resource management"],
  "Microsoft Office 365": ["cloud computing", "human resource management"],
  "MailChimp": ["email marketing"],
  "Zendesk Support": ["customer relationship", "live chat and messaging"],
  "Mailgun": ["email marketing"],
  "Amazon SES": ["email marketing", "cloud computing"],
  "Amazon Web Services": ["cloud computing"],
  "Google Cloud DNS": ["cloud computing"],
  "Intercom": ["customer relationship", "live chat and messaging"],
  "Tawk.to": ["customer relationship", "live chat and messaging"],
  "Next.js": ["programming languages", "website hosting"],
  "Expressjs": ["programming languages"],
  "Google AdSense": ["advertising"],
  "Nodejs": ["programming languages"],
  "Salesforce Pardot": ["email marketing", "customer relationship"],
  "Stripe": ["payment gateways"],
  "Java": ["programming languages"],
  "Mixpanel": ["website analytics"],
  "Drupal": ["website hosting", "e-commerce platforms"],
  "Marketo": ["email marketing", "customer relationship", "event management"],
  "Amazon S3": ["cloud computing", "website hosting"],
  "Segment": ["website analytics"],
  "Zendesk JavaScript API": ["customer relationship", "live chat and messaging"],
  "React": ["programming languages"],
  "Zendesk Chat": ["customer relationship", "live chat and messaging"],
  "Pardot": ["email marketing", "customer relationship"],
  "Eventbrite": ["event management"],
  "Hubspot CMS": ["e-commerce platforms", "website hosting"],
  "Marketo Email": ["email marketing", "customer relationship", "event management"],
  "Microsoft ASP.NET": ["programming languages", "cloud computing"],
  "WooCommerce": ["e-commerce platforms"],
  "Vuejs": ["programming languages"]
}
